Settings:
  #启用的相机编号
  #CameraIds: [114514, 31415926, 0, 7]
  CameraIds: [0]
  #串口编号
  SerialPortIds: [0]
  CheckVersion:
    Enable: false
    # AutoUpdate: false TODO
  # (0/1) == (RED/BLUE)
  TargetColor: 1