BaudSpeed: 115200
Databits: 8
Stopbits: 1
Parity: 78
UsbPath: /dev/bus/usb/003/003
OpenById: true

SendSetting:
  Ids: [0]
  0:
    Head: 0x5a
    Tail: 0xa5
  1:
    Head: 0x6b
    Tail: 0xb6
  2:
    Head: 0x7c
    Tail: 0xc7
ReceiveSetting:
  Ids: [0]
  0:
    Head: 0x5a
    Tail: 0xa5
    Check:
      Head: true
      Tail: true
      Crc: true
  1:
    Head: 0x6b
    Tail: 0xb6
    Check:
      Head: true
      Tail: true
      Crc: true
  2:
    Head: 0x7c
    Tail: 0xc7
    Check:
      Head: true
      Tail: true
      Crc: true
