LoadIds: [0]

0:
  CameraID: 0
  ReceiveID: 0
  SendId: 0
  FireControl:
    Armor:
      BulletPitch: 75.0
      # shu yue xiao yue wang you
      OffestYaw: [
        -4.0, # 0 ~ 0.85
        -4.3, # 0.85 ~ 1.35
        -2.8, # 1.35 ~ 1.85
        -2.8, # 1.85 ~ 2.35
        -2.5, # 2.35 ~ 2.85
        -2.5, # 2.85 ~ 3.35
        -2.3, # 3.35 ~ 3.85
        -2.3, # 3.85 ~ 4.35
        -2.6, # 4.35 ~ 4.85
        -2.8, # 4.85 ~ 5.35
        -2.8, # 5.35 ~ 5.85
        -1.8, # 5.85 ~ 6.35
        -1, # 6.35 ~ 6.85
        -1.8, # 6.85 ~ 7.35
        -1.8 # 7.35 ~ 7.85
      ]
      # shu yue xiao yue wang shang
      OffestPitch: [
        2.0, # 0 ~ 0.85
        2.0, # 0.85 ~ 1.35
        3.0, # 1.35 ~ 1.85
        2.0, # 1.85 ~ 2.35
        2.0, # 2.35 ~ 2.85
        2.0, # 2.85 ~ 3.35
        2.0, # 3.35 ~ 3.85
        2.0, # 3.85 ~ 4.35
        1.5, # 4.35 ~ 4.85
        1.5, # 4.85 ~ 5.35
        1.5, # 5.35 ~ 5.85
        1.5, # 5.85 ~ 6.35
        1, # 6.35 ~ 6.85
        1, # 6.85 ~ 7.35
        1.3 # 7.35 ~ 7.85
      ]
    Outpost:
      BulletPitch: 90.0
      OffestYaw: [
        -4.0, # 0 ~ 1
        -4.3, # 1 ~ 2
        -1.7, # 2 ~ 3
        -1.7, # 3 ~ 4
        -4.0, # 4 ~ 5
        -4.8, # 5 ~ 6
        -4 # 6 ~ 7
      ]
      # shu yue xiao yue wang shang
      OffestPitch: [
        1.0, # 0 ~ 1
        -0.5, # 1 ~ 2
        -0.5, # 2 ~ 3
        0.5, # 3 ~ 4
        -1.0, # 4 ~ 5
        0.8, # 5 ~ 6
        0 # 6 ~ 7
      ]
  Light:
    Splited: true
    FilterMake: true
    Area:
      max: 999999
      min: -1
    Rate:
      max: 0.7
      min: -1
    Angle:
      max: 30
      min: -1
  Armor:
    LengthRate:
      max: 1
      min: 0.80
    Angle:
      max: 25
      min: -1
    AngleMate:
      max: 45
      min: -1
    Rate:
      max: 1
      min: 0.225
    Area:
      max: 999999
      min: -1
    Debug:
      angle: false
      angleMate: false
      rate: false
      lengthRate: false
      area: false
    Classify:
      enable: true
      #0 onnx 1 digit
      mode: 1
      minConfidence:
        onxx: 40
        digit: 40
  Predict:
    enable: false
    #0 point 1 motion
    mode: 0
    # true - will update result by future point
    updateResult: true
    point:
      armor:
        VxRate: 1
        VyRate: 1
        dt: 0.12
        # K: [0.976236,0.976236,0.96,1.12]
      outpost:
        # cosK = cos(15 / 360.0*3.1415926)
        # v_rate = 0.976236 * cosK = 0.942986799
        VxRate: 0.942986799
        VyRate: 0.942986799
        dt: 0.12
        # K: [0.976236,0.976236,0.96,1.12]
    motion:
      armor:
        maxTargetHeight: 1.2
        maxMatchDistance: 0.2
        maxMatchYawDiff: 0.5
        trackingThres: 3
        dt: 0.12
        kalman:
          rYaw: 0.005
          rX: 0.0001
      outpost:
  ShowSrc: true