LoadIds: [0]

0:
  CameraID: 0
  ReceiveID: 0
  SendId: 0
  ShowSrc: true
  Light:
    DrawAll: false
    Splited: true
    FilterMake: true
    Area:
      max: 999999
      min: -1
    Rate:
      max: 0.75
      min: 0.08
    Angle:
      max: 45
      min: -1
    Debug:
      angle: false
      rate: false
      area: false
  Armor:
    DrawAll: false  
    LengthRate:
      max: 1
      min: 0.8
    Angle:
      max: 5
      min: -1
    AngleMate:
      max: 15
      min: -1
    Rate:
      max: 2.5
      min: 0.15
    Area:
      max: 999999
      min: -1
    Debug:
      angle: false
      angleMate: false
      rate: false
      lengthRate: false
      area: false
    Classify:
      enable: true
      #0 onnx 1 digit
      mode: 1
      minConfidence:
        onxx: 40
        digit: 
          ONE: 65
          TWO: 50
          THREE: 50
          FOUR: 50
          FIVE: 50
          OUTPOST: 50
          GUARD: 50
          BASE: 50
          NEGATIVE: 50
  Predict:
    enable: true
    #0 point 1 motion
    mode: 0
    # true - will update result by future point
    updateResult: true
    point:
      armor:
        VxRate: 1
        VyRate: 1
        dt: 0.12
        # K: [0.976236,0.976236,0.96,1.12]
      outpost:
        # cosK = cos(15 / 360.0*3.1415926)
        # v_rate = 0.976236 * cosK = 0.942986799
        VxRate: 0.942986799
        VyRate: 0.942986799
        dt: 0.12
        # K: [0.976236,0.976236,0.96,1.12]
    motion:
      armor:
        maxTargetHeight: 1.2
        maxMatchDistance: 0.2
        maxMatchYawDiff: 0.5
        trackingThres: 3
        dt: 0.12
        kalman:
          rYaw: 0.005
          rX: 0.0001
      outpost:
  FireControl:
    MaxHeight: 2.1
    MaxFabPitch: 2.0
    MaxFabYaw: 2.0
    Armor:
      BulletPitch: 75.0
      # shu yue xiao yue wang you
      OffestYaw: [
        0, # 0 ~ 0.85
        0, # 0.85 ~ 1.35
        0, # 1.35 ~ 1.85
        0, # 1.85 ~ 2.35
        0, # 2.35 ~ 2.85
        -0.5, # 2.85 ~ 3.35
        -0.5, # 3.35 ~ 3.85
        0.0, # 3.85 ~ 4.35
        0, # 4.35 ~ 4.85
        0, # 4.85 ~ 5.35
        0, # 5.35 ~ 5.85
        0, # 5.85 ~ 6.35
        0, # 6.35 ~ 6.85
        0, # 6.85 ~ 7.35
        0 # 7.35 ~ 7.85
      ]
      # shu yue xiao yue wang shang
      OffestPitch: [
        0, # 0 ~ 0.85
        0, # 0.85 ~ 1.35
        0, # 1.35 ~ 1.85
        0, # 1.85 ~ 2.35
        0, # 2.35 ~ 2.85
        0, # 2.85 ~ 3.35
        0, # 3.35 ~ 3.85
        0.0, # 3.85 ~ 4.35
        0, # 4.35 ~ 4.85
        0, # 4.85 ~ 5.35
        0, # 5.35 ~ 5.85
        0, # 5.85 ~ 6.35
        0, # 6.35 ~ 6.85
        0, # 6.85 ~ 7.35
        0 # 7.35 ~ 7.85
      ]
    Outpost:
      BulletPitch: 90.0
      OffestYaw: [
        0, # 0 ~ 0.85
        0, # 0.85 ~ 1.35
        0, # 1.35 ~ 1.85
        0, # 1.85 ~ 2.35
        -1.5, # 2.35 ~ 2.85
        -1.5, # 2.85 ~ 3.35
        -1.5, # 3.35 ~ 3.85
        2.0, # 3.85 ~ 4.35
        -1.0, # 4.35 ~ 4.85
        -2.8, # 4.85 ~ 5.35
        -2.8, # 5.35 ~ 5.85
        -1.8, # 5.85 ~ 6.35
        -1, # 6.35 ~ 6.85
        -1.8, # 6.85 ~ 7.35
        -1.8 # 7.35 ~ 7.85
      ]
      # shu yue xiao yue wang shang
      OffestPitch: [
        0, # 0 ~ 0.85
        0, # 0.85 ~ 1.35
        1.0, # 1.35 ~ 1.85
        -2.8, # 1.85 ~ 2.35
        0.8, # 2.35 ~ 2.85
        0.8, # 2.85 ~ 3.35
        5.0, # 3.35 ~ 3.85
        5.5, # 3.85 ~ 4.35
        -2.6, # 4.35 ~ 4.85
        -2.8, # 4.85 ~ 5.35
        -2.8, # 5.35 ~ 5.85
        -1.8, # 5.85 ~ 6.35
        -1, # 6.35 ~ 6.85
        -1.8, # 6.85 ~ 7.35
        -1.8 # 7.35 ~ 7.85
      ]